// <auto-generated />
using System;
using LinkBook.Services.UrlAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkBook.Services.UrlAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinkBook.Services.UrlAPI.Models.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<string>("AliasUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(max)");

                    b.Property<byte>("Favorite")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("TINYINT")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("NVARCHAR(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(max)");

                    b.HasKey("Id");

                    b.ToTable("Links", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
